name: basic_authentication_flutter_challenge
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  # Useful to know if token is expired
  jwt_decoder: ^2.0.1
  # Be as secure as possible 🤓
  flutter_secure_storage: ^6.0.0
  # Use get_it as a service locator, to access the injected dependencies
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true