name: basic_authentication_flutter_challenge
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Will use http for... well, http calls :)
  http: ^0.13.5
  # Local Storage
  hive: ^2.2.3
  # Will use get_it as a service locator, to access the injected dependencies
  get_it: ^7.2.0
  # Will use Stacked for MVVM implementaion 
  stacked: ^2.3.15
  # To access app documents directory
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true